site_name: Flutterの前のDart
theme:
  name: material
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - def_list
  - abbr
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
extra_javascript:
  - js/highlight.min.js
  - javascripts/config.js
extra_css:
  - css/vs.min.css
  - css/custom.css
# use_directory_urls: false

nav:
  - はじめに: index.md
  - 第1章 変数: 01/index.md
  - 第2章 演算子: 02/index.md
  - 第3章 制御フロー: 03/index.md
  - 第4章 関数: 04/index.md
  - 第5章 クラス: 05/index.md
