site_name: JavaからのFlutter
theme:
  name: material
  language: 'ja'
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - attr_list
  - def_list
  - abbr
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
extra_javascript:
  - js/highlight.min.js
  - javascripts/config.js
extra_css:
  - css/vs.min.css
  - css/custom.css
# use_directory_urls: false

nav:
  - Dart:
    - はじめに: index.md
    - 第1章 変数: dart/01/index.md
    - 第2章 演算子: dart/02/index.md
    - 第3章 制御フロー: dart/03/index.md
    - 第4章 関数: dart/04/index.md
    - 第5章 クラス: dart/05/index.md
  - Flutter:
    - 1. サンプルアプリケーションを読む: flutter/01/index.md
    - 2. レイアウト: flutter/02/index.md
    - 3. UI部品: flutter/03/index.md
    - 4. 複雑なレイアウト: flutter/04/index.md
    - 5. 簡単なアプリを作ってみよう: flutter/05/index.md
