site_name: Flutter
theme:
  name: material
  language: 'ja'
  features:
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.keys
  - def_list
  - abbr
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
extra_javascript:
  - js/highlight.min.js
  - javascripts/config.js
extra_css:
  - css/vs.min.css
  - css/custom.css
# use_directory_urls: false

nav:
  - Dart:
    - はじめに: index.md
    - 第1章 変数: dart01/index.md
    - 第2章 演算子: dart02/index.md
    - 第3章 制御フロー: dart03/index.md
    - 第4章 関数: dart04/index.md
    - 第5章 クラス: dart05/index.md
